//
// Created by Leslie on 15.10.2024.
//

#ifndef FIMBULWINTERENGINE_COMPONENTREGISTER_HPP
#define FIMBULWINTERENGINE_COMPONENTREGISTER_HPP


class ComponentRegister {
};


#endif //FIMBULWINTERENGINE_COMPONENTREGISTER_HPP
