//
// Created by Leslie on 15.10.2024.
//

#ifndef FIMBULWINTERENGINE_COMPONENTSTORAGE_HPP
#define FIMBULWINTERENGINE_COMPONENTSTORAGE_HPP

class ComponentStorage {

};

#endif //FIMBULWINTERENGINE_COMPONENTSTORAGE_HPP
